
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x1f\xc8\xa3\x0ff\x00\x92E\xb6\xa9V\xa8\x10\xa40\xe2'
    
_lr_action_items = {'NUMBER':([0,],[1,]),'$end':([1,2,],[-1,0,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'factor':([0,],[2,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> factor","S'",1,None,None,None),
  ('factor -> NUMBER','factor',1,'p_factor_num','pars.py',34),
]
