language: python
python: 2.7
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py32
    - TOX_ENV=py33
    - TOX_ENV=pypy
matrix:
    allow_failures:
        - env: TOX_ENV=py33
install:
    - pip install tox
    - wget https://bitbucket.org/pypy/pypy/get/default.tar.bz2 -O `pwd`/../pypy.tar.bz2
    - tar -xf `pwd`/../pypy.tar.bz2 -C `pwd`/../
script: PYPY_LOCATION=`python -c "import glob; import os; print os.path.abspath(glob.glob('../pypy-pypy*')[0])"` tox -e $TOX_ENV
notifications:
    email: false

